QFILE=/home/weicon/textgen/qtest/pack_erp4_chat_prompt/iq4_prompt_config.json
#TESTS="[\"batch_1\\\"\,\"nshot_1\"]"
TESTS="[\"sarah\"]"
#TESTS="[\"tom_\"]"
sh run_cp.sh /mnt/old/root/new_data/silicon-maid-7b.Q6_K.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/old/root/new_data/starling-lm-7b-alpha.Q6_K.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/vigostral-7b-chat.Q5_K_M.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/old/root/new_data/solar-10.7b-instruct-v1.0.Q5_K_M.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/orca-2-7b.Q6_K.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/mistral-ft-optimized-1227.Q6_K.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/neural-chat-7b-v3-16k-q8_0.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/llama-2-7b-chat.Q5_K_M.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/Synatra_7b_0_3_rp_q4km.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/opus-v0-7b.Q5_K_M.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/mythomist-7b.q6_K.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/MergeMonster-Decensored-7b-20231130.q6_K.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/una-cybertron-7b-v2-bf16.Q6_K.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/mistral-7b-instruct-v0.1.Q5_K_M.gguf_by_TheBloke_20230927.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/Mistral-7B-claude-chat.q5_k_m.gguf_by_Undi95_20230927.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/Mistral-ClaudeLimaRP-v3-7B.q5_k_m.gguf_by_Undi95_20230928.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/PetrolLM-7B.q5_k_m.gguf_by_Undi95_20230928.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/synthia-7b-v1.3.Q5_K_M.gguf_by_TheBloke_20230929.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/Mistral-RP-0.1-7B.q5_k_m.gguf_by_Undi95_20230929.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/samantha-mistral-7b.Q5_K_M.gguf_by_TheBloke_20230930.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/kimiko-mistral-7b.Q5_K_M.gguf_by_TheBloke_20230930.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/Medusa-1.3-L2-7B.q5_K_M.gguf_by_Sao10K_20230930.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/MistRP-v1.1-7B.q8_0.gguf_by_Undi95_20231001.gguf $QFILE "$TESTS"
sh run_cp.sh /mnt/p_ml/ggmls/Llama-2-7b-Mistral.q5_k_m.gguf_by_Undi95_20231001.gguf $QFILE "$TESTS"
sh run_13b.sh /mnt/p_ml/Noromaid-13b-v0.3-T4.q5_k_m.gguf $QFILE "$TESTS"
sh run_13b.sh /mnt/p_ml/mythomax-l2-13b.Q5_K_M.gguf $QFILE "$TESTS"
sh run_13b.sh /mnt/p_ml/Unholy-v1.1-13B.q5_K_M.gguf $QFILE "$TESTS"
sh run_13b.sh /mnt/p_ml/Stheno-1.8-L2-13B.q5_K_M.gguf $QFILE "$TESTS"
sh run_13b.sh /mnt/p_ml/Utopia-13B.q5_k_m.gguf $QFILE "$TESTS"
sh run_13b.sh /mnt/p_ml/cat-v1.0-13b.Q5_K_M.gguf $QFILE "$TESTS"
